### ISSUE TITLE
How do I get the trees to grow?

### ISSUE THREAD

**Issue by GoodAtBowling** [VulpesStella/OreTree#1]
I've crafted a diamond tree and placed it on deepslate diamond ore in the 1.18.1 version, but after about an hour the tree still refuses to grow. I don't understand what exactly I need to do to grow this tree. I have planted the tree in a cave underground and surrounded it with light, but please let me know if I am doing something incorrectly.

**Comment by VulpesStella** [comment]
1. Trees need [natural light](https://github.com/MikhailTapio/OreTree/blob/1.18/src/main/java/com/teamfractal/ore_tree/common/block/base/OreSaplingBlock.java#L111) to grow.
2. The diamond tree has a lower growth possibility by default.
3. Check if any block prevents the tree to grow, a 5x5 space above should be left.
4. The trees' growth is activated by random tick, which is very often a factor of uncertainty. Check [this](https://minecraft.fandom.com/wiki/Tick) for its mechanism.

**Comment by VulpesStella** [comment]
Also, you can directly catalyze the tree by right-clicking diamond on it. It has a catalysis possibility as well, configurable.

**Comment by GoodAtBowling** [comment]
ah I see. Thanks for the help

**Comment by VulpesStella** [comment]
Hope you enjoy~

**Comment by TheNextPley** [comment]
Can we get please that it drops the specific sapling too and leaves drop the ore like the normal tree the sticks.
Also, it is a very nice mod.

**Comment by VulpesStella** [comment]
> 

That will be too OP… And actually I'm too lazy to add more leaves for the trees😂
