### ISSUE TITLE
Exception in server tick loop I java.lang.NoClassDefFoundError: net/minecraft/class_638

### ISSUE THREAD

**Issue by TheButterbrotMan** [VulpesStella/OreTree#2]
Server crashes when feeding Diamond Ore Tree with Diamonds, to let him faster grow.

https://pastebin.com/CWV8m7QJ

**Comment by VulpesStella** [comment]
It seems Minecraft server didn't know how to locate a client-side class👀, anyway I'll try to fix it.

**Comment by VulpesStella** [comment]
Fixed in [9e35be6](https://github.com/MikhailTapio/OreTree/commit/3a258b860523862f6956cb1358c262cd5933cbee).
