### ISSUE TITLE
Unable to Place in Bonsatrees

### ISSUE THREAD

**Issue by holty07** [VulpesStella/OreTree#3]
Hi there,

Running Ore Trees v1.18-X-0.2.4 and Bonsai Trees 3.0.4 I am unable to grow any of the ore trees in Bonsai Trees. 

Let me know if there is a log I can provide to help.

**Comment by VulpesStella** [comment]
Hello! What type of ore tree were you planting? Did you choose the right dirts?

**Comment by holty07** [comment]
Hey, sorry, I have since realised it was only the copper ore tree that wouldn't go into the pot at all for me. The iron ore tree has gone in but I need to get silk touch so I can get an ore to place in there to test if it is growing. :)

Also just quickly if I change the setting to allow grow on dirt should that work in a bonsai pot too?

**Comment by VulpesStella** [comment]
> Hey, sorry, I have since realised it was only the copper ore tree that wouldn't go into the pot at all for me. The iron ore tree has gone in but I need to get silk touch so I can get an ore to place in there to test if it is growing. :)
> 
> Also just quickly if I change the setting to allow grow on dirt should that work in a bonsai pot too?

Hmmm, nope. But you can add a bonsai tree "dirt" recipe for that by yourself :D
(Sorry for the late reply, I have been busy with so many things these days)
