### ISSUE TITLE
Log Block incompatible with loot modifiers

### ISSUE THREAD

**Issue by brnbrd** [VulpesStella/OreTree#7]
The way you've implemented your [log block](https://github.com/MikhailTapio/OreTree/blob/1.18/src/main/java/com/teamfractal/ore_tree/common/block/base/OreInlaidLogBlock.java) (by overriding `Block#getDrops` and not providing a loot_table JSON), you are not allowing its generated loot to be noticed by loot_modifiers, such as enchantments. Your mod should really remove this unnecessary override, and just provide a loot_table JSON.

**Comment by VulpesStella** [comment]
It's added.
