### ISSUE TITLE
1.19 ?

### ISSUE THREAD

**Issue by staviq** [VulpesStella/OreTree#9]
Why would it be released for 1.19 if it's not compatible with 1.19.2 ?

`Unmet dependency listing:
	 - Mod 'OreTree' (ore_tree) 1.0.1 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!`

**Comment by Hiddenisme** [comment]
I second this as well. Curse states it works for 1.19.2 but yeah that same message pops up.

**Comment by VulpesStella** [comment]
Modify "1.19" to "*" and try again. Also it's an oversight by me bruh.

**Comment by VulpesStella** [comment]
If nothing else I'll close the issue.
